window.PUBLICATIONS = [
  {
    "title": "GeoRelight: Learning Joint Geometrical Relighting and Reconstruction with Flexible Multi-Modal Diffusion Transformers",
    "authors": "Y Xue, R Liang, E Zakharov, T Bagautdinov, C Cao, G Nam, S Saito, ...",
    "venue": "arXiv preprint arXiv:2604.20715",
    "year": "2026",
    "citations": "5",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:vDijr-p_gm4C",
    "paper_url": "https://arxiv.org/abs/2604.20715",
    "teaser": "assets/images/georelight.webp",
    "bib": "assets/bib/xue2026georelight.bib",
    "cv_bib": true,
    "pdf_url": "https://arxiv.org/pdf/2604.20715"
  },
  {
    "title": "3dgh: 3d head generation with composable hair and face",
    "authors": "C He, J Li, T Kirschstein, A Sevastopolsky, S Saito, Q Tan, J Romero, ...",
    "venue": "ACM Transactions on Graphics (TOG) 44 (4), 1-12",
    "year": "2025",
    "citations": "7",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:ipzZ9siozwsC",
    "paper_url": "https://dl.acm.org/doi/abs/10.1145/3731211",
    "teaser": "assets/images/publications/3dgh-3d-head-generation-with-composable-ha-4d85259c33.webp",
    "bib": "assets/bib/he20253dgh.bib",
    "cv_bib": true,
    "pdf_url": "https://arxiv.org/pdf/2506.20875"
  },
  {
    "title": "Atlas: Decoupling skeletal and shape parameters for expressive parametric human modeling",
    "authors": "J Park, J Romero, S Saito, F Prada, T Shiratori, Y Xu, F Bogo, SI Yu, ...",
    "venue": "2025 IEEE/CVF International Conference on Computer Vision (ICCV), 6508-6518",
    "year": "2025",
    "citations": "12",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:EkHepimYqZsC",
    "pdf_url": "https://openaccess.thecvf.com/content/ICCV2025/papers/Park_ATLAS_Decoupling_Skeletal_and_Shape_Parameters_for_Expressive_Parametric_Human_ICCV_2025_paper.pdf",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/11445698/",
    "teaser": "assets/images/atlas.webp",
    "bib": "assets/bib/park2025atlas.bib",
    "cv_bib": true
  },
  {
    "title": "Avat3r: Large animatable gaussian reconstruction model for high-fidelity 3d head avatars",
    "authors": "T Kirschstein, J Romero, A Sevastopolsky, M Nießner, S Saito",
    "venue": "2025 IEEE/CVF International Conference on Computer Vision (ICCV), 12089-12100",
    "year": "2025",
    "citations": "53",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:0KyAp5RtaNEC",
    "pdf_url": "https://arxiv.org/pdf/2502.20220",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/11446296/",
    "teaser": "assets/images/avat3r.webp",
    "bib": "assets/bib/kirschstein2025avat3r.bib",
    "cv_bib": true
  },
  {
    "title": "Drivable 3d gaussian avatars",
    "authors": "W Zielonka, T Bagautdinov, S Saito, M Zollhöfer, J Thies, J Romero",
    "venue": "2025 International Conference on 3D Vision (3DV), 979-990",
    "year": "2025",
    "citations": "210",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:_Re3VWB3Y0AC",
    "pdf_url": "https://arxiv.org/pdf/2311.08581",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/11125564/",
    "teaser": "assets/images/drivable-gaussian-avatars.webp",
    "bib": "assets/bib/zielonka2023drivable.bib",
    "cv_bib": true
  },
  {
    "title": "Fresa: Feedforward reconstruction of personalized skinned avatars from few images",
    "authors": "R Wang, F Prada, Z Wang, Z Jiang, C Yin, J Li, S Saito, I Santesteban, ...",
    "venue": "2025 IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR …",
    "year": "2025",
    "citations": "8",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:uc_IGeMz5qoC",
    "pdf_url": "https://openaccess.thecvf.com/content/CVPR2025/papers/Wang_FRESA_Feedforward_Reconstruction_of_Personalized_Skinned_Avatars_from_Few_Images_CVPR_2025_paper.pdf",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/11093588/",
    "teaser": "assets/images/publications/fresa-feedforward-reconstruction-of-person-20ca051473.webp",
    "bib": "assets/bib/wang2025fresa.bib",
    "cv_bib": true
  },
  {
    "title": "Mhr: Momentum human rig",
    "authors": "A Ferguson, AAA Osman, B Bescos, C Stoll, C Twigg, C Lassner, D Otte, ...",
    "venue": "arXiv preprint arXiv:2511.15586",
    "year": "2025",
    "citations": "36",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:zLWjf1WUPmwC",
    "pdf_url": "https://arxiv.org/pdf/2511.15586",
    "paper_url": "https://arxiv.org/abs/2511.15586",
    "teaser": "assets/images/publications/mhr-momentum-human-rig-bc7fdd4641.webp",
    "bib": "assets/bib/ferguson2026mhr.bib",
    "cv_bib": true
  },
  {
    "title": "Relightable full-body gaussian codec avatars",
    "authors": "S Wang, T Simon, I Santesteban, T Bagautdinov, J Li, V Agrawal, F Prada, ...",
    "venue": "Proceedings of the Special Interest Group on Computer Graphics and …",
    "year": "2025",
    "citations": "24",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:fEOibwPWpKIC",
    "pdf_url": "https://arxiv.org/pdf/2501.14726",
    "paper_url": "https://dl.acm.org/doi/abs/10.1145/3721238.3730739",
    "teaser": "assets/images/publications/relightable-full-body-gaussian-codec-avata-4897ef3f94.webp",
    "bib": "assets/bib/wang2025relightable.bib",
    "cv_bib": true
  },
  {
    "title": "Codec avatar studio: Paired human captures for complete, driveable, and generalizable avatars",
    "authors": "J Martinez, E Kim, J Romero, T Bagautdinov, S Saito, SI Yu, S Anderson, ...",
    "venue": "Advances in Neural Information Processing Systems 37, 83008-83023",
    "year": "2024",
    "citations": "52",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:35r97b3x0nAC",
    "pdf_url": "https://proceedings.neurips.cc/paper_files/paper/2024/file/9712b78386cebdc3db7f1a48c2d20edb-Paper-Datasets_and_Benchmarks_Track.pdf",
    "paper_url": "https://proceedings.neurips.cc/paper_files/paper/2024/hash/9712b78386cebdc3db7f1a48c2d20edb-Abstract-Datasets_and_Benchmarks_Track.html",
    "teaser": "assets/images/publications/codec-avatar-studio-paired-human-captures--9ed8ecc50e.webp",
    "bib": "assets/bib/martinez2025AVA256.bib",
    "cv_bib": true
  },
  {
    "title": "Diffusion shape prior for wrinkle-accurate cloth registration",
    "authors": "J Guo, F Prada, D Xiang, J Romero, C Wu, HS Park, T Shiratori, S Saito",
    "venue": "2024 International Conference on 3D Vision (3DV), 790-799",
    "year": "2024",
    "citations": "16",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:ZfRJV9d4-WMC",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/10550774/",
    "teaser": "assets/images/publications/diffusion-shape-prior-for-wrinkle-accurate-d90e564dec.webp",
    "bib": "assets/bib/guo2024diffusion.bib",
    "cv_bib": true,
    "pdf_url": "https://arxiv.org/pdf/2311.05828"
  },
  {
    "title": "From audio to photoreal embodiment: Synthesizing humans in conversations",
    "authors": "E Ng, J Romero, T Bagautdinov, S Bai, T Darrell, A Kanazawa, A Richard",
    "venue": "2024 IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR …",
    "year": "2024",
    "citations": "128",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:tzM49s52ZIMC",
    "pdf_url": "https://arxiv.org/pdf/2401.01885",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/10657577/",
    "teaser": "assets/images/publications/from-audio-to-photoreal-embodiment-synthes-cfd199edf9.webp",
    "bib": "assets/bib/ng2024audio.bib",
    "cv_bib": true
  },
  {
    "title": "The Lips, the Teeth, the tip of the Tongue: LTT Tracking",
    "authors": "F Rasras, S Pidhorskyi, T Simon, H Paz, H Wen, J Saragih, J Romero",
    "venue": "SIGGRAPH Asia 2024 Conference Papers, 1-11",
    "year": "2024",
    "citations": "4",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:-_dYPAW6P2MC",
    "pdf_url": "https://dl.acm.org/doi/pdf/10.1145/3680528.3687691",
    "paper_url": "https://dl.acm.org/doi/abs/10.1145/3680528.3687691",
    "bib": "assets/bib/rasras2024ltt.bib",
    "cv_bib": true
  },
  {
    "title": "URhand: Universal relightable hands",
    "authors": "Z Chen, G Moon, K Guo, C Cao, S Pidhorskyi, T Simon, R Joshi, Y Dong, ...",
    "venue": "Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern …",
    "year": "2024",
    "citations": "29",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:2KloaMYe4IUC",
    "pdf_url": "https://openaccess.thecvf.com/content/CVPR2024/papers/Chen_URHand_Universal_Relightable_Hands_CVPR_2024_paper.pdf",
    "paper_url": "https://openaccess.thecvf.com/content/CVPR2024/html/Chen_URHand_Universal_Relightable_Hands_CVPR_2024_paper.html",
    "teaser": "assets/images/publications/urhand-universal-relightable-hands-c852b79186.webp",
    "bib": "assets/bib/chen2024urhand.bib",
    "cv_bib": true
  },
  {
    "title": "SMPL: A skinned multi-person linear model",
    "authors": "M Loper, N Mahmood, J Romero, G Pons-Moll, MJ Black",
    "venue": "Seminal Graphics Papers: Pushing the Boundaries, Volume 2, 851-866",
    "year": "2023",
    "citations": "7229",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:9ZlFYXVOiuMC",
    "paper_url": "https://dl.acm.org/doi/abs/10.1145/3596711.3596800",
    "teaser": "assets/images/smpl.webp",
    "bib": "assets/bib/SMPL-2015.bib",
    "cv_bib": true,
    "pdf_url": "https://files.is.tue.mpg.de/black/papers/SMPL2015.pdf"
  },
  {
    "title": "AutoAvatar: Autoregressive neural fields for dynamic avatar modeling",
    "authors": "Z Bai, T Bagautdinov, J Romero, M Zollhöfer, P Tan, S Saito",
    "venue": "European Conference on Computer Vision, 222-239",
    "year": "2022",
    "citations": "7",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:dQ2og3OwTAUC",
    "pdf_url": "https://arxiv.org/pdf/2203.13817",
    "paper_url": "https://link.springer.com/chapter/10.1007/978-3-031-20068-7_13",
    "teaser": "assets/images/publications/autoavatar-autoregressive-neural-fields-fo-29a158e995.webp",
    "bib": "assets/bib/bai2022autoavatar.bib",
    "cv_bib": true
  },
  {
    "title": "Dressing avatars: Deep photorealistic appearance for physically simulated clothing",
    "authors": "D Xiang, T Bagautdinov, T Stuyck, F Prada, J Romero, W Xu, S Saito, ...",
    "venue": "ACM Transactions on Graphics (TOG) 41 (6), 1-15",
    "year": "2022",
    "citations": "99",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:UHK10RUVsp4C",
    "pdf_url": "https://arxiv.org/pdf/2206.15470",
    "paper_url": "https://dl.acm.org/doi/abs/10.1145/3550454.3555456",
    "teaser": "assets/images/publications/dressing-avatars-deep-photorealistic-appea-d256db13f2.webp",
    "bib": "assets/bib/xiang2022dressing.bib",
    "cv_bib": true
  },
  {
    "title": "Embodied hands: Modeling and capturing hands and bodies together",
    "authors": "J Romero, D Tzionas, MJ Black",
    "venue": "arXiv preprint arXiv:2201.02610",
    "year": "2022",
    "citations": "2099",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:NaGl4SEjCO4C",
    "pdf_url": "https://arxiv.org/pdf/2201.02610",
    "paper_url": "https://arxiv.org/abs/2201.02610",
    "teaser": "assets/images/mano.webp",
    "bib": "assets/bib/MANO-SIGGRAPHASIA-2017.bib",
    "cv_bib": true
  },
  {
    "title": "Human body measurement estimation with adversarial augmentation",
    "authors": "N Ruiz, M Bellver, T Bolkart, A Arora, MC Lin, J Romero, R Bala",
    "venue": "2022 International Conference on 3D Vision (3DV), 219-230",
    "year": "2022",
    "citations": "16",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:Fu2w8maKXqMC",
    "pdf_url": "https://arxiv.org/pdf/2210.05667",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/10044417/",
    "teaser": "assets/images/publications/human-body-measurement-estimation-with-adv-0f8e86e96d.webp",
    "bib": "assets/bib/ruiz2022human.bib",
    "cv_bib": true
  },
  {
    "title": "Learning realistic human reposing using cyclic self-supervision with 3d shape, pose, and appearance consistency",
    "authors": "S Sanyal, A Vorobiov, T Bolkart, M Loper, B Mohler, LS Davis, J Romero, ...",
    "venue": "Proceedings of the IEEE/CVF International Conference on Computer Vision …",
    "year": "2021",
    "citations": "27",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:ZuybSZzF8UAC",
    "pdf_url": "https://openaccess.thecvf.com/content/ICCV2021/papers/Sanyal_Learning_Realistic_Human_Reposing_Using_Cyclic_Self-Supervision_With_3D_Shape_ICCV_2021_paper.pdf",
    "paper_url": "https://openaccess.thecvf.com/content/ICCV2021/html/Sanyal_Learning_Realistic_Human_Reposing_Using_Cyclic_Self-Supervision_With_3D_Shape_ICCV_2021_paper.html",
    "teaser": "assets/images/publications/learning-realistic-human-reposing-using-cy-adfca0202c.webp",
    "bib": "assets/bib/sanyal2021learning.bib",
    "cv_bib": true
  },
  {
    "title": "Smplpix: Neural avatars from 3d human models",
    "authors": "S Prokudin, MJ Black, J Romero",
    "venue": "2021 IEEE Winter Conference on Applications of Computer Vision (WACV), 1809-1818",
    "year": "2021",
    "citations": "99",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:LjlpjdlvIbIC",
    "pdf_url": "https://arxiv.org/pdf/2008.06872",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/9423274/",
    "teaser": "assets/images/smplpix.webp",
    "bib": "assets/bib/SMPLpix-WACV-2020.bib",
    "cv_bib": true
  },
  {
    "title": "Learning multi-human optical flow",
    "authors": "A Ranjan, DT Hoffmann, D Tzionas, S Tang, J Romero, MJ Black",
    "venue": "International Journal of Computer Vision 128 (4), 873-890",
    "year": "2020",
    "citations": "55",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:u9iWguZQMMsC",
    "pdf_url": "https://arxiv.org/pdf/1910.11667",
    "paper_url": "https://link.springer.com/article/10.1007/s11263-019-01279-w",
    "teaser": "assets/images/publications/learning-multi-human-optical-flow-388bb44bb7.webp",
    "bib": "assets/bib/Ranjan-IJCV-2020.bib",
    "cv_bib": true
  },
  {
    "title": "Decoding subcategories of human bodies from both body-and face-responsive cortical regions",
    "authors": "C Foster, M Zhao, J Romero, MJ Black, BJ Mohler, A Bartels, I Bülthoff",
    "venue": "Neuroimage 202, 116085",
    "year": "2019",
    "citations": "16",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:UxriW0iASnsC",
    "pdf_url": "https://www.sciencedirect.com/science/article/pii/S1053811919306731",
    "paper_url": "https://www.sciencedirect.com/science/article/pii/S1053811919306731",
    "bib": "assets/bib/Foster-NeuroImage-2019.bib",
    "cv_bib": true
  },
  {
    "title": "Efficient learning on point clouds with basis point sets",
    "authors": "S Prokudin, C Lassner, J Romero",
    "venue": "Proceedings of the IEEE International Conference on Computer Vision, 0-0",
    "year": "2019",
    "citations": "224",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:SP6oXDckpogC",
    "pdf_url": "https://arxiv.org/pdf/1908.09186",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/9022338/",
    "teaser": "assets/images/publications/efficient-learning-on-point-clouds-with-ba-61bacc1839.webp",
    "bib": "assets/bib/Prokudin_2019_ICCV.bib",
    "cv_bib": true
  },
  {
    "title": "Facsimile: Fast and accurate scans from an image in less than a second",
    "authors": "D Smith, M Loper, X Hu, P Mavroidis, J Romero",
    "venue": "2019 IEEE/CVF International Conference on Computer Vision (ICCV), 5329-5338",
    "year": "2019",
    "citations": "72",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:uWQEDVKXjbEC",
    "pdf_url": "https://arxiv.org/pdf/1909.00883",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/9008396/",
    "teaser": "assets/images/facsimile.webp",
    "bib": "assets/bib/Smith_2019_ICCV.bib",
    "cv_bib": true
  },
  {
    "title": "Assessing body image in anorexia nervosa using biometric self-avatars in virtual reality: Attitudinal components rather than visual body size estimation are distorted",
    "authors": "SC Mölbert, A Thaler, BJ Mohler, S Streuber, J Romero, MJ Black, S Zipfel, ...",
    "venue": "Psychological medicine 48 (4), 642-653",
    "year": "2018",
    "citations": "219",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:7PzlFSSx8tAC",
    "pdf_url": "https://www.cambridge.org/core/services/aop-cambridge-core/content/view/A111D545D17E2F260D62434C254F3951/S0033291717002008a.pdf/assessing_body_image_in_anorexia_nervosa_using_biometric_selfavatars_in_virtual_reality_attitudinal_components_rather_than_visual_body_size_estimation_are_distorted.pdf",
    "paper_url": "https://www.cambridge.org/core/journals/psychological-medicine/article/assessing-body-image-in-anorexia-nervosa-using-biometric-selfavatars-in-virtual-reality-attitudinal-components-rather-than-visual-body-size-estimation-are-distorted/A111D545D17E2F260D62434C254F3951",
    "teaser": "assets/images/publications/assessing-body-image-in-anorexia-nervosa-u-c3c3b4c53b.webp",
    "bib": "assets/bib/Molbert-PM-2017.bib",
    "cv_bib": true
  },
  {
    "title": "Body size estimation of self and others in females varying in BMI",
    "authors": "A Thaler, MN Geuss, SC Mölbert, KE Giel, S Streuber, J Romero, ...",
    "venue": "PloS one 13 (2), e0192152",
    "year": "2018",
    "citations": "88",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:RYcK_YlVTxYC",
    "pdf_url": "https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0192152&type=printable",
    "paper_url": "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0192152",
    "teaser": "assets/images/publications/body-size-estimation-of-self-and-others-in-641613633b.webp",
    "bib": "assets/bib/Thaler-PLOS-2018.bib",
    "cv_bib": true
  },
  {
    "title": "Learning an infant body model from RGB-D data for accurate full body motion analysis",
    "authors": "N Hesse, S Pujades, J Romero, MJ Black, C Bodensteiner, M Arens, ...",
    "venue": "International Conference on Medical Image Computing and Computer-Assisted …",
    "year": "2018",
    "citations": "122",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:OU6Ihb5iCvQC",
    "pdf_url": "https://files.is.tue.mpg.de/black/papers/miccai18.pdf",
    "paper_url": "https://link.springer.com/chapter/10.1007/978-3-030-00928-1_89",
    "teaser": "assets/images/publications/learning-an-infant-body-model-from-rgb-d-d-5f3af85d43.webp",
    "bib": "assets/bib/Hesse-MICCAI-2018.bib",
    "cv_bib": true
  },
  {
    "title": "Learning human optical flow",
    "authors": "A Ranjan, J Romero, MJ Black",
    "venue": "arXiv preprint arXiv:1806.05666",
    "year": "2018",
    "citations": "37",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:ldfaerwXgEUC",
    "pdf_url": "https://arxiv.org/pdf/1806.05666",
    "paper_url": "https://arxiv.org/abs/1806.05666",
    "teaser": "assets/images/publications/learning-human-optical-flow-4861b5cf79.webp",
    "bib": "assets/bib/Ranjan-BMVC-2018.bib",
    "cv_bib": true
  },
  {
    "title": "Robust Physics‐based Motion Retargeting with Realistic Body Shapes",
    "authors": "M Al Borno, L Righetti, MJ Black, SL Delp, E Fiume, J Romero",
    "venue": "Computer Graphics Forum 37 (8), 81-92",
    "year": "2018",
    "citations": "41",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:g5m5HwL7SMYC",
    "pdf_url": "http://nmbl.stanford.edu/wp-content/uploads/sca18-fin.pdf",
    "paper_url": "https://onlinelibrary.wiley.com/doi/abs/10.1111/cgf.13514",
    "teaser": "assets/images/publications/robust-physics-based-motion-retargeting-wi-6d323ccd7f.webp",
    "bib": "assets/bib/romero2018RobustPhysicsbasedMotionRetargeting.bib",
    "cv_bib": false
  },
  {
    "title": "Shape estimation of subcutaneous adipose tissue using an articulated statistical shape model",
    "authors": "SY Yeo, J Romero, M Loper, J Machann, M Black",
    "venue": "Computer Methods in Biomechanics and Biomedical Engineering: Imaging …",
    "year": "2018",
    "citations": "9",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:L8Ckcad2t8MC",
    "pdf_url": "https://institute-tue.ellis.eu/uploads/publication_attachment/attachment/275/cmbbe1.pdf",
    "paper_url": "https://www.tandfonline.com/doi/abs/10.1080/21681163.2016.1163508",
    "teaser": "assets/images/publications/shape-estimation-of-subcutaneous-adipose-t-4e649afec5.webp",
    "bib": "assets/bib/Yeo-CMBBE-2016.bib",
    "cv_bib": true
  },
  {
    "title": "Visual perception and evaluation of photo-realistic self-avatars from 3D body scans in males and females",
    "authors": "A Thaler, I Piryankova, JK Stefanucci, S Pujades, S de La Rosa, ...",
    "venue": "Frontiers in ICT 5, 18",
    "year": "2018",
    "citations": "50",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:3s1wT3WcHBgC",
    "pdf_url": "https://inria.hal.science/hal-02162162/file/thalerFICT18.pdf",
    "paper_url": "https://www.frontiersin.org/journals/ict/articles/10.3389/fict.2018.00018/full",
    "teaser": "assets/images/publications/visual-perception-and-evaluation-of-photo--55377187d9.webp",
    "bib": "assets/bib/Thaler-Frontiers-2018.bib",
    "cv_bib": true
  },
  {
    "title": "A simple yet effective baseline for 3d human pose estimation",
    "authors": "J Martinez, R Hossain, J Romero, JJ Little",
    "venue": "2017 IEEE international conference on computer vision (ICCV), 2659-2668",
    "year": "2017",
    "citations": "2235",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:j3f4tGmQtD8C",
    "pdf_url": "https://arxiv.org/pdf/1705.03098",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/8237550/",
    "teaser": "assets/images/publications/a-simple-yet-effective-baseline-for-3d-hum-9ce42d59e8.webp",
    "bib": "assets/bib/JMartinez-ICCV-2017.bib",
    "cv_bib": true
  },
  {
    "title": "Decoding categories shared by the face and body",
    "authors": "C Foster, M Zhao, J Romero, MJ Black, BJ Mohler, A Bartels",
    "venue": "18th Conference of Junior Neuroscientists of Tübingen (NeNa 2017), 24",
    "year": "2017",
    "citations": "",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:pqnbT2bcN3wC",
    "paper_url": "https://scholar.google.com/scholar?cluster=7222632383686659447&hl=en&oi=scholarr",
    "bib": "assets/bib/romero2017DecodingCategoriesSharedBy.bib",
    "cv_bib": false
  },
  {
    "title": "Dynamic FAUST: Registering human bodies in motion",
    "authors": "F Bogo, J Romero, G Pons-Moll, MJ Black",
    "venue": "2017 IEEE conference on computer vision and pattern recognition (CVPR), 5573 …",
    "year": "2017",
    "citations": "523",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:BqipwSGYUEgC",
    "pdf_url": "https://files.is.tue.mpg.de/black/papers/dfaust2017.pdf",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/8100074/",
    "teaser": "assets/images/publications/dynamic-faust-registering-human-bodies-in--a509fad1d3.webp",
    "bib": "assets/bib/dfaust-CVPR-2017.bib",
    "cv_bib": true
  },
  {
    "title": "Gender differences in visual perception of own body weight",
    "authors": "A Thaler, I Piryankova, MN Geuss, JK Stefanucci, S de la Rosa, ...",
    "venue": "40th European Conference on Visual Perception (ECVP 2017), 103",
    "year": "2017",
    "citations": "",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:HoB7MX3m0LUC",
    "paper_url": "https://scholar.google.com/scholar?cluster=15552278608716431365&hl=en&oi=scholarr",
    "bib": "assets/bib/romero2017GenderDifferencesInVisual.bib",
    "cv_bib": false
  },
  {
    "title": "Learning a model of facial shape and expression from 4D scans.",
    "authors": "T Li, T Bolkart, MJ Black, H Li, J Romero",
    "venue": "ACM Trans. Graph. 36 (6), 194:1-194:17",
    "year": "2017",
    "citations": "1901",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:J_g5lzvAfSwC",
    "pdf_url": "https://3dvar.com/Li2017Learning.pdf",
    "paper_url": "https://3dvar.com/Li2017Learning.pdf",
    "teaser": "assets/images/flame.webp",
    "bib": "assets/bib/FLAME-2017.bib",
    "cv_bib": true
  },
  {
    "title": "Learning from synthetic humans",
    "authors": "G Varol, J Romero, X Martin, N Mahmood, MJ Black, I Laptev, C Schmid",
    "venue": "Proceedings of the IEEE conference on computer vision and pattern …",
    "year": "2017",
    "citations": "1399",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:qUcmZB5y_30C",
    "pdf_url": "https://openaccess.thecvf.com/content_cvpr_2017/papers/Varol_Learning_From_Synthetic_CVPR_2017_paper.pdf",
    "paper_url": "https://openaccess.thecvf.com/content_cvpr_2017/html/Varol_Learning_From_Synthetic_CVPR_2017_paper.html",
    "teaser": "assets/images/surreal.webp",
    "bib": "assets/bib/Varol-CVPR-2017.bib",
    "cv_bib": true
  },
  {
    "title": "On human motion prediction using recurrent neural networks",
    "authors": "J Martinez, MJ Black, J Romero",
    "venue": "2017 IEEE Conference on computer vision and pattern recognition (CVPR), 4674 …",
    "year": "2017",
    "citations": "1492",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:R3hNpaxXUhUC",
    "pdf_url": "https://arxiv.org/pdf/1705.02445",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/8099980/",
    "teaser": "assets/images/publications/on-human-motion-prediction-using-recurrent-e5f0c91675.webp",
    "bib": "assets/bib/Martinez-CVPR-2017.bib",
    "cv_bib": true
  },
  {
    "title": "Towards accurate marker-less human shape and pose estimation over time",
    "authors": "Y Huang, F Bogo, C Lassner, A Kanazawa, PV Gehler, J Romero, I Akhter, ...",
    "venue": "2017 international conference on 3D vision (3DV), 421-430",
    "year": "2017",
    "citations": "270",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:nb7KW1ujOQ8C",
    "pdf_url": "https://arxiv.org/pdf/1707.07548",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/8374596/",
    "teaser": "assets/images/publications/towards-accurate-marker-less-human-shape-a-ef2541c738.webp",
    "bib": "assets/bib/MuVS-3DV-2017.bib",
    "cv_bib": true
  },
  {
    "title": "Unite the people: Closing the loop between 3d and 2d human representations",
    "authors": "C Lassner, J Romero, M Kiefel, F Bogo, MJ Black, PV Gehler",
    "venue": "2017 IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 4704 …",
    "year": "2017",
    "citations": "752",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:hC7cP41nSMkC",
    "pdf_url": "https://arxiv.org/pdf/1701.02468",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/8099983/",
    "teaser": "assets/images/publications/unite-the-people-closing-the-loop-between--89f916eb6e.webp",
    "bib": "assets/bib/Lassner-UP-2017.bib",
    "cv_bib": true
  },
  {
    "title": "Appealing avatars from 3D body scans: Perceptual effects of stylization",
    "authors": "R Fleming, BJ Mohler, J Romero, MJ Black, M Breidt",
    "venue": "International Joint Conference on Computer Vision, Imaging and Computer …",
    "year": "2016",
    "citations": "15",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:KxtntwgDAa4C",
    "pdf_url": "https://shura.shu.ac.uk/11507/1/Fleming%20appealing%20female.pdf",
    "paper_url": "https://link.springer.com/chapter/10.1007/978-3-319-64870-5_9",
    "teaser": "assets/images/publications/appealing-avatars-from-3d-body-scans-perce-01d9169a34.webp",
    "bib": "assets/bib/Fleming-Avatar-2017.bib",
    "cv_bib": true
  },
  {
    "title": "Appealing Female Avatars from 3D Body Scans: Perceptual Effects of Stylization.",
    "authors": "R Fleming, BJ Mohler, J Romero, MJ Black, M Breidt",
    "venue": "VISIGRAPP (1: GRAPP), 335-345",
    "year": "2016",
    "citations": "30",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:xtRiw3GOFMkC",
    "pdf_url": "https://pdfs.semanticscholar.org/efb9/1c8e68dde9df3758df2d98dcac37b0098d31.pdf",
    "paper_url": "https://pdfs.semanticscholar.org/efb9/1c8e68dde9df3758df2d98dcac37b0098d31.pdf",
    "teaser": "assets/images/publications/appealing-female-avatars-from-3d-body-scan-3c893b463d.webp",
    "bib": "assets/bib/Fleming-GRAPP-2016.bib",
    "cv_bib": true
  },
  {
    "title": "Coupling adaptive batch sizes with learning rates",
    "authors": "L Balles, J Romero, P Hennig",
    "venue": "arXiv preprint arXiv:1612.05086",
    "year": "2016",
    "citations": "166",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:-f6ydRqryjwC",
    "pdf_url": "https://arxiv.org/pdf/1612.05086",
    "paper_url": "https://arxiv.org/abs/1612.05086",
    "teaser": "assets/images/publications/coupling-adaptive-batch-sizes-with-learnin-111ff0177c.webp",
    "bib": "assets/bib/balles2017coupling.bib",
    "cv_bib": true
  },
  {
    "title": "Keep it SMPL: Automatic estimation of 3D human pose and shape from a single image",
    "authors": "F Bogo, A Kanazawa, C Lassner, P Gehler, J Romero, MJ Black",
    "venue": "European conference on computer vision, 561-578",
    "year": "2016",
    "citations": "2345",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:ZeXyd9-uunAC",
    "pdf_url": "https://arxiv.org/pdf/1607.08128",
    "paper_url": "https://link.springer.com/chapter/10.1007/978-3-319-46454-1_34",
    "teaser": "assets/images/keep-it-smpl.webp",
    "bib": "assets/bib/Bogo-ECCV-2016.bib",
    "cv_bib": true
  },
  {
    "title": "Dataset Suite for Benchmarking Perception in Robotics",
    "authors": "A Ahmad, P Lima, J Romero, M Loper, MJ Black",
    "venue": "IROS 2015 Workshop: Open Forum on Evaluation of Results, Replication of …",
    "year": "2015",
    "citations": "",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:WqliGbK-hY8C",
    "paper_url": "https://scholar.google.com/scholar?cluster=9847699356470489607&hl=en&oi=scholarr",
    "bib": "assets/bib/romero2015DatasetSuiteForBenchmarking.bib",
    "cv_bib": false
  },
  {
    "title": "Detailed full-body reconstructions of moving people from monocular RGB-D sequences",
    "authors": "F Bogo, MJ Black, M Loper, J Romero",
    "venue": "Proceedings of the IEEE international conference on computer vision, 2300-2308",
    "year": "2015",
    "citations": "266",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:4DMP91E08xMC",
    "pdf_url": "https://www.cv-foundation.org/openaccess/content_iccv_2015/papers/Bogo_Detailed_Full-Body_Reconstructions_ICCV_2015_paper.pdf",
    "paper_url": "https://www.cv-foundation.org/openaccess/content_iccv_2015/html/Bogo_Detailed_Full-Body_Reconstructions_ICCV_2015_paper.html",
    "teaser": "assets/images/publications/detailed-full-body-reconstructions-of-movi-4069de63df.webp",
    "bib": "assets/bib/Bogo-ICCV-2015.bib",
    "cv_bib": true
  },
  {
    "title": "Dyna: A model of dynamic human shape in motion",
    "authors": "G Pons-Moll, J Romero, N Mahmood, MJ Black",
    "venue": "Acm Transactions on Graphics (TOG) 34 (4), 1-14",
    "year": "2015",
    "citations": "432",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:qxL8FJ1GzNcC",
    "paper_url": "https://dl.acm.org/doi/abs/10.1145/2766993",
    "teaser": "assets/images/publications/dyna-a-model-of-dynamic-human-shape-in-mot-627e4374c4.webp",
    "bib": "assets/bib/Dyna-SIGGRAPH-2015.bib",
    "cv_bib": true
  },
  {
    "title": "FlowCap: 2D human pose from optical flow",
    "authors": "J Romero, M Loper, MJ Black",
    "venue": "German conference on pattern recognition, 412-423",
    "year": "2015",
    "citations": "29",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:Wp0gIr-vW9MC",
    "pdf_url": "https://is.mpg.de/uploads/publication_attachment/attachment/237/main42.pdf",
    "paper_url": "https://link.springer.com/chapter/10.1007/978-3-319-24947-6_34",
    "bib": "assets/bib/romero-gcpr-2015.bib",
    "cv_bib": true
  },
  {
    "title": "The grasp taxonomy of human grasp types",
    "authors": "T Feix, J Romero, HB Schmiedmayer, AM Dollar, D Kragic",
    "venue": "IEEE Transactions on human-machine systems 46 (1), 66-77",
    "year": "2015",
    "citations": "1533",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:aqlVkmm33-oC",
    "pdf_url": "https://www.eng.yale.edu/grablab/pubs/Feix_THMS2016.pdf",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/7243327/",
    "teaser": "assets/images/grasp-taxonomy.webp",
    "bib": "assets/bib/romero-THMS-2016.bib",
    "cv_bib": true
  },
  {
    "title": "Automated detection of new or evolving melanocytic lesions using a 3D body model",
    "authors": "F Bogo, J Romero, E Peserico, MJ Black",
    "venue": "International Conference on Medical Image Computing and Computer-Assisted …",
    "year": "2014",
    "citations": "23",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:KlAtU1dfN6UC",
    "pdf_url": "https://files.is.tue.mpg.de/fbogo/papers/Bogo_MICCAI2014.pdf",
    "paper_url": "https://link.springer.com/chapter/10.1007/978-3-319-10404-1_74",
    "teaser": "assets/images/publications/automated-detection-of-new-or-evolving-mel-44836ead5d.webp",
    "bib": "assets/bib/bogo-miccai-2014.bib",
    "cv_bib": true
  },
  {
    "title": "Can I recognize my body's weight? The influence of shape and texture on the perception of self",
    "authors": "IV Piryankova, JK Stefanucci, J Romero, S De La Rosa, MJ Black, ...",
    "venue": "ACM Transactions on Applied Perception (TAP) 11 (3), 1-18",
    "year": "2014",
    "citations": "76",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:Zph67rFs4hoC",
    "pdf_url": "https://dl.acm.org/doi/pdf/10.1145/2641568",
    "paper_url": "https://dl.acm.org/doi/abs/10.1145/2641568",
    "bib": "assets/bib/SAP-2014.bib",
    "cv_bib": true
  },
  {
    "title": "FAUST: Dataset and evaluation for 3D mesh registration",
    "authors": "F Bogo, J Romero, M Loper, MJ Black",
    "venue": "Proceedings of the IEEE conference on computer vision and pattern …",
    "year": "2014",
    "citations": "1021",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:3fE2CSJIrl8C",
    "pdf_url": "https://www.cv-foundation.org/openaccess/content_cvpr_2014/papers/Bogo_FAUST_Dataset_and_2014_CVPR_paper.pdf",
    "paper_url": "https://www.cv-foundation.org/openaccess/content_cvpr_2014/html/Bogo_FAUST_Dataset_and_2014_CVPR_paper.html",
    "teaser": "assets/images/publications/faust-dataset-and-evaluation-for-3d-mesh-r-ebe48b1e14.webp",
    "bib": "assets/bib/Bogo-CVPR-2014.bib",
    "cv_bib": true
  },
  {
    "title": "Robot arm pose estimation through pixel-wise part classification",
    "authors": "J Bohg, J Romero, A Herzog, S Schaal",
    "venue": "2014 IEEE International Conference on Robotics and Automation (ICRA), 3143-3150",
    "year": "2014",
    "citations": "92",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:kNdYIx-mwKoC",
    "pdf_url": "https://www.researchgate.net/profile/Jeannette-Bohg/publication/281668188_Robot_arm_pose_estimation_through_pixel-wise_part_classification/links/5784b36f08aee45b84445ffd/Robot-arm-pose-estimation-through-pixel-wise-part-classification.pdf",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/6907311/",
    "bib": "assets/bib/2014_ICRA_brhs.bib",
    "cv_bib": true
  },
  {
    "title": "Estimating human pose with flowing puppets",
    "authors": "S Zuffi, J Romero, C Schmid, MJ Black",
    "venue": "proceedings of the IEEE International Conference on Computer Vision, 3312-3319",
    "year": "2013",
    "citations": "69",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:MXK_kJrjxJIC",
    "pdf_url": "https://www.cv-foundation.org/openaccess/content_iccv_2013/papers/Zuffi_Estimating_Human_Pose_2013_ICCV_paper.pdf",
    "paper_url": "https://www.cv-foundation.org/openaccess/content_iccv_2013/html/Zuffi_Estimating_Human_Pose_2013_ICCV_paper.html",
    "teaser": "assets/images/publications/estimating-human-pose-with-flowing-puppets-204a3d1e58.webp",
    "bib": "assets/bib/Zuffi-ICCV-2013.bib",
    "cv_bib": true
  },
  {
    "title": "Extracting postural synergies for robotic grasping",
    "authors": "J Romero, T Feix, CH Ek, H Kjellström, D Kragic",
    "venue": "IEEE Transactions on Robotics 29 (6), 1342-1352",
    "year": "2013",
    "citations": "67",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:5nxA0vEk-isC",
    "pdf_url": "https://people.kth.se/~hedvig/publications/tro_13.pdf",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/6564441/",
    "teaser": "assets/images/publications/extracting-postural-synergies-for-robotic--8c25866d37.webp",
    "bib": "assets/bib/romero_tro_2013.bib",
    "cv_bib": true
  },
  {
    "title": "Non-parametric hand pose estimation with object context",
    "authors": "J Romero, H Kjellström, CH Ek, D Kragic",
    "venue": "Image and Vision Computing 31 (8), 555-564",
    "year": "2013",
    "citations": "51",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:0EnyYjriUFMC",
    "pdf_url": "https://is.mpg.de/uploads/publication_attachment/attachment/131/2013_ivc_rkek.pdf",
    "paper_url": "https://www.sciencedirect.com/science/article/pii/S0262885613000656",
    "teaser": "assets/images/publications/non-parametric-hand-pose-estimation-with-o-bb75bc8f0d.webp",
    "bib": "assets/bib/Romero2013555.bib",
    "cv_bib": true
  },
  {
    "title": "A metric for comparing the anthropomorphic motion capability of artificial hands",
    "authors": "T Feix, J Romero, CH Ek, HB Schmiedmayer, D Kragic",
    "venue": "IEEE transactions on robotics 29 (1), 82-93",
    "year": "2012",
    "citations": "126",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:UebtZRa9Y70C",
    "pdf_url": "https://hal.science/hal-01139344/document",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/6313928/",
    "bib": "assets/bib/Feix-TRO-2012.bib",
    "cv_bib": true
  },
  {
    "title": "Grade your hand toolbox",
    "authors": "T Feix, J Romero, C Ek, HB Schmiedmayer, D Kragic",
    "venue": "Feix, T., New Haven, CT, accessed Feb 8, 2016",
    "year": "2012",
    "citations": "6",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:W7OEmFMy1HYC",
    "pdf_url": "http://grasp.xief.net/data/gradeHand2.2.pdf",
    "paper_url": "http://grasp.xief.net/data/gradeHand2.2.pdf",
    "bib": "assets/bib/romero2012GradeYourHandToolbox.bib",
    "cv_bib": false
  },
  {
    "title": "Visual servoing on unknown objects",
    "authors": "X Gratal, J Romero, J Bohg, D Kragic",
    "venue": "Mechatronics 22 (4), 423-435",
    "year": "2012",
    "citations": "38",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:roLk4NBRz8UC",
    "pdf_url": "https://www.academia.edu/download/46128966/Visual_servoing_on_unknown_objects20160601-17241-1tbh9dj.pdf",
    "paper_url": "https://www.sciencedirect.com/science/article/pii/S0957415811001528",
    "bib": "assets/bib/Gratal-Mechatronics-2011.bib",
    "cv_bib": true
  },
  {
    "title": "From human to robot grasping",
    "authors": "J Romero",
    "venue": "KTH Royal Institute of Technology",
    "year": "2011",
    "citations": "10",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:LkGwnXOMwfcC",
    "paper_url": "https://scholar.google.com/scholar?cluster=3898290385250285685&hl=en&oi=scholarr",
    "bib": "assets/bib/romero2011FromHumanToRobot.bib",
    "cv_bib": false
  },
  {
    "title": "Virtual visual servoing for real-time robot pose estimation",
    "authors": "X Gratal, J Romero, D Kragic",
    "venue": "IFAC Proceedings Volumes 44 (1), 9017-9022",
    "year": "2011",
    "citations": "27",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:eQOLeE2rZwMC",
    "pdf_url": "https://skoge.folk.ntnu.no/prost/proceedings/ifac11-proceedings/data/html/papers/2970.pdf",
    "paper_url": "https://www.sciencedirect.com/science/article/pii/S1474667016450597",
    "teaser": "assets/images/publications/virtual-visual-servoing-for-real-time-robo-0dca47b69f.webp",
    "bib": "assets/bib/Gratal-IFAC-2011.bib",
    "cv_bib": true
  },
  {
    "title": "Visual object-action recognition: Inferring object affordances from human demonstration",
    "authors": "H Kjellström, J Romero, D Kragić",
    "venue": "Computer Vision and Image Understanding 115 (1), 81-90",
    "year": "2011",
    "citations": "319",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:qjMakFHDy7sC",
    "pdf_url": "https://people.kth.se/~hedvig/publications/cviu_11.pdf",
    "paper_url": "https://www.sciencedirect.com/science/article/pii/S107731421000175X",
    "teaser": "assets/images/publications/visual-object-action-recognition-inferring-17d92a739d.webp",
    "bib": "assets/bib/Kjellstrom-CVIU-2010.bib",
    "cv_bib": true
  },
  {
    "title": "Hands in action: real-time 3D reconstruction of hands in interaction with objects",
    "authors": "J Romero, H Kjellström, D Kragic",
    "venue": "2010 IEEE International Conference on Robotics and Automation, 458-463",
    "year": "2010",
    "citations": "160",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:9yKSN-GCB0IC",
    "pdf_url": "https://fileadmin.cs.lth.se/ai/Proceedings/ICRA2010/MainConference/data/papers/1553.pdf",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/5509753/",
    "teaser": "assets/images/publications/hands-in-action-real-time-3d-reconstructio-3c30043918.webp",
    "bib": "assets/bib/romero2010b.bib",
    "cv_bib": true
  },
  {
    "title": "Spatio-temporal modeling of grasping actions",
    "authors": "J Romero, T Feix, H Kjellström, D Kragic",
    "venue": "2010 IEEE/RSJ International Conference on Intelligent Robots and Systems …",
    "year": "2010",
    "citations": "74",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:Tyk-4Ss8FVUC",
    "pdf_url": "https://www.researchgate.net/profile/Hedvig-Kjellstroem/publication/224199895_Spatio-temporal_modeling_of_grasping_actions/links/54d8d7930cf25013d040188a/Spatio-temporal-modeling-of-grasping-actions.pdf",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/5650701/",
    "teaser": "assets/images/publications/spatio-temporal-modeling-of-grasping-actio-eeb7f6fe70.webp",
    "bib": "assets/bib/Romero-IROS-2010.bib",
    "cv_bib": true
  },
  {
    "title": "Understanding Manifolds of Grasping Actions",
    "authors": "J Romero, T Feix, H Kjellström, D Kragic",
    "venue": "",
    "year": "2010",
    "citations": "2",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:YsMSGLbcyi4C",
    "pdf_url": "https://fileadmin.cs.lth.se/ai/Proceedings/ICRA2010/ICRA%202010%20WS/W5/pdf/9.pdf",
    "paper_url": "https://fileadmin.cs.lth.se/ai/Proceedings/ICRA2010/ICRA%202010%20WS/W5/pdf/9.pdf",
    "teaser": "assets/images/publications/understanding-manifolds-of-grasping-action-3e102b9e36.webp",
    "bib": "assets/bib/romero2010UnderstandingManifoldsOfGrasping.bib",
    "cv_bib": false
  },
  {
    "title": "A comprehensive grasp taxonomy",
    "authors": "T Feix, R Pawlik, HB Schmiedmayer, J Romero, D Kragic",
    "venue": "Robotics, science and systems: workshop on understanding the human hand for …",
    "year": "2009",
    "citations": "438",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:u-x6o8ySG0sC",
    "pdf_url": "https://is.mpg.de/uploads/publication_attachment/attachment/109/abstract.pdf",
    "paper_url": "https://is.mpg.de/uploads/publication_attachment/attachment/109/abstract.pdf",
    "teaser": "assets/images/publications/a-comprehensive-grasp-taxonomy-b773f4dc60.webp",
    "bib": "assets/bib/Feix-RSSws-2010.bib",
    "cv_bib": true
  },
  {
    "title": "Grasp recognition and mapping on humanoid robots",
    "authors": "M Do, J Romero, H Kjellström, P Azad, T Asfour, D Kragic, R Dillmann",
    "venue": "2009 9th IEEE-RAS International Conference on Humanoid Robots, 465-471",
    "year": "2009",
    "citations": "30",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:zYLM7Y9cAGgC",
    "pdf_url": "https://h2t.iar.kit.edu/pdf/Do2009.pdf",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/5379538/",
    "teaser": "assets/images/publications/grasp-recognition-and-mapping-on-humanoid--0b096f0fdc.webp",
    "bib": "assets/bib/Do-Humanoids-2009.bib",
    "cv_bib": true
  },
  {
    "title": "Modeling and evaluation of human-to-robot mapping of grasps",
    "authors": "J Romero, H Kjellstrom, D Kragic",
    "venue": "2009 International Conference on Advanced Robotics, 1-6",
    "year": "2009",
    "citations": "35",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:Y0pCki6q_DkC",
    "pdf_url": "https://people.kth.se/~hedvig/publications/icar_09.pdf",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/5174785/",
    "teaser": "assets/images/publications/modeling-and-evaluation-of-human-to-robot--f96da5d16b.webp",
    "bib": "assets/bib/Romero-ICAR-2009.bib",
    "cv_bib": true
  },
  {
    "title": "Monocular real-time 3D articulated hand pose estimation",
    "authors": "J Romero, H Kjellström, D Kragic",
    "venue": "2009 9th IEEE-RAS International Conference on Humanoid Robots, 87-92",
    "year": "2009",
    "citations": "128",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:2osOgNQ5qMEC",
    "pdf_url": "https://www.csc.kth.se/~hedvig/publications/humanoids_09.pdf",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/5379596/",
    "teaser": "assets/images/publications/monocular-real-time-3d-articulated-hand-po-b7973a1b4b.webp",
    "bib": "assets/bib/romeroHUMANOIDS09.bib",
    "cv_bib": true
  },
  {
    "title": "Dynamic time warping for binocular hand tracking and reconstruction",
    "authors": "J Romero, D Kragic, V Kyrki, A Argyros",
    "venue": "2008 IEEE International Conference on Robotics and Automation, 2289-2294",
    "year": "2008",
    "citations": "17",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:IjCSPb-OGe4C",
    "pdf_url": "https://www.ics.forth.gr/~argyros/mypapers/2008_05_icra_dynamic_time_warping.pdf",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/4543555/",
    "teaser": "assets/images/publications/dynamic-time-warping-for-binocular-hand-tr-b60947dbfd.webp",
    "bib": "assets/bib/Romero-ICRA-2008.bib",
    "cv_bib": true
  },
  {
    "title": "Human-to-robot mapping of grasps",
    "authors": "J Romero, H Kjellstrm, D Kragic",
    "venue": "Proceedings of IEEE/RSJ International Conference on Intelligent Robots and …",
    "year": "2008",
    "citations": "29",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:UeHWp8X0CEIC",
    "pdf_url": "https://www.researchgate.net/profile/Hedvig-Kjellstroem/publication/228863783_Human-to-robot_mapping_of_grasps/links/54d8d7910cf2970e4e79d370/Human-to-robot-mapping-of-grasps.pdf",
    "paper_url": "https://www.researchgate.net/profile/Hedvig-Kjellstroem/publication/228863783_Human-to-robot_mapping_of_grasps/links/54d8d7910cf2970e4e79d370/Human-to-robot-mapping-of-grasps.pdf",
    "bib": "assets/bib/romero2008HumanToRobotMapping.bib",
    "cv_bib": false
  },
  {
    "title": "Simultaneous visual recognition of manipulation actions and manipulated objects",
    "authors": "H Kjellström, J Romero, D Martínez, D Kragić",
    "venue": "European conference on computer vision, 336-349",
    "year": "2008",
    "citations": "108",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:u5HHmVD_uO8C",
    "pdf_url": "https://www.csc.kth.se/~hedvig/publications/eccv_08.pdf",
    "paper_url": "https://link.springer.com/chapter/10.1007/978-3-540-88688-4_25",
    "teaser": "assets/images/publications/simultaneous-visual-recognition-of-manipul-ee424c8f69.webp",
    "bib": "assets/bib/Kjellstrom-ECCV-2008.bib",
    "cv_bib": true
  },
  {
    "title": "Visual recognition of grasps for human-to-robot mapping",
    "authors": "H Kjellstrom, J Romero, D Kragic",
    "venue": "2008 IEEE/RSJ International Conference on Intelligent Robots and Systems …",
    "year": "2008",
    "citations": "49",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:d1gkVwhDpl0C",
    "pdf_url": "https://www.researchgate.net/profile/Danica-Kragic/publication/221063464_Visual_Recognition_of_Grasps_for_Human-to-Robot_Mapping/links/0deec52b935fdf372f000000/Visual-Recognition-of-Grasps-for-Human-to-Robot-Mapping.pdf",
    "paper_url": "https://ieeexplore.ieee.org/abstract/document/4650917/",
    "bib": "assets/bib/romero2008VisualRecognitionOfGrasps.bib",
    "cv_bib": false
  },
  {
    "title": "Binocular Hand Tracking and Pose Estimation",
    "authors": "J Romero",
    "venue": "Master Thesis, CVAP/CAS, KTH, Stockholm",
    "year": "2007",
    "citations": "1",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:ufrVoPGSRksC",
    "paper_url": "https://scholar.google.com/scholar?cluster=3719100589662114744&hl=en&oi=scholarr",
    "bib": "assets/bib/romero2007BinocularHandTrackingAnd.bib",
    "cv_bib": false
  },
  {
    "title": "3.13 Deep Learning from Unstructured, Uncalibrated Views",
    "authors": "J Romero",
    "venue": "3D Morphable Models, 28, 0",
    "year": "",
    "citations": "",
    "url": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Wx62iOsAAAAJ&pagesize=100&citation_for_view=Wx62iOsAAAAJ:tKAzc9rXhukC",
    "paper_url": "https://d-nb.info/1365183726/34#page=13",
    "bib": "assets/bib/romerond313DeepLearning.bib",
    "cv_bib": false
  }
];
